//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSArray, NSString, WeatherTemperatureFormatter;

@interface HourlyScrollerBeltView : UICollectionView <UICollectionViewDelegate, UICollectionViewDataSource>
{
    id <HourlyScrollerBeltDelegate> _hourlyScrollerDelegate;
    WeatherTemperatureFormatter *_temperatureFormatter;
    NSArray *_forecasts;
}

+ (void)cacheFormattedTimeString:(id)arg1 forTimeString:(id)arg2;
+ (id)formattedTimeStringFromCache:(id)arg1;
+ (id)nts_formattedTimeStringCache;
+ (void)cacheFormattedTemperatureString:(id)arg1 forTemperatureString:(id)arg2;
+ (id)formattedTemperatureStringFromCache:(id)arg1;
+ (id)nts_formattedTemperatureStringCache;
+ (double)height;
@property(copy, nonatomic) NSArray *forecasts; // @synthesize forecasts=_forecasts;
@property(retain, nonatomic) WeatherTemperatureFormatter *temperatureFormatter; // @synthesize temperatureFormatter=_temperatureFormatter;
@property(nonatomic) __weak id <HourlyScrollerBeltDelegate> hourlyScrollerDelegate; // @synthesize hourlyScrollerDelegate=_hourlyScrollerDelegate;
- (void).cxx_destruct;
- (void)userTextSizeDidChange;
- (void)resetLocale;
- (void)clearCaches;
- (id)condensedTimeInRegionFormatForString:(id)arg1;
- (id)formattedTemperatureForString:(id)arg1;
- (void)_temperatureUnitDidChange;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)resetScrollerOffsets;
- (void)updateForecasts:(id)arg1;
- (void)prepareForReuse;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

