//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewController.h"

@class NSArray, UIImageView, WAWeatherCollectionFooterViewCell;

@interface WAAbstractCollectionViewController : UICollectionViewController
{
    _Bool _isTransitioningSizes;
    NSArray *_cities;
    id <WACollectionViewCellTransitionDelegate> _transitionDelegate;
    UIImageView *_statusBarShadow;
    WAWeatherCollectionFooterViewCell *_footerCell;
}

+ (_Bool)_shouldForwardViewWillTransitionToSize;
@property(retain, nonatomic) WAWeatherCollectionFooterViewCell *footerCell; // @synthesize footerCell=_footerCell;
@property(retain, nonatomic) UIImageView *statusBarShadow; // @synthesize statusBarShadow=_statusBarShadow;
@property(nonatomic) _Bool isTransitioningSizes; // @synthesize isTransitioningSizes=_isTransitioningSizes;
@property(nonatomic) __weak id <WACollectionViewCellTransitionDelegate> transitionDelegate; // @synthesize transitionDelegate=_transitionDelegate;
@property(copy, nonatomic) NSArray *cities; // @synthesize cities=_cities;
- (void).cxx_destruct;
- (unsigned long long)transitionMode;
- (void)configureCell:(id)arg1 withLayoutAttributes:(id)arg2;
- (void)prepareForReuse;
- (_Bool)canStartTransitionToMode:(unsigned long long)arg1;
- (void)animateDeletionOfRowWithCell:(id)arg1;
- (void)orderSubviews;
- (void)didUpdateWeather;
- (void)updateUIForCity:(id)arg1;
- (void)reloadData;
- (void)showStatusBarShadow:(_Bool)arg1 animate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)updateContentOffsetForCell:(id)arg1 indexPath:(id)arg2;
- (void)collectionView:(id)arg1 didEndDisplayingSupplementaryView:(id)arg2 forElementOfKind:(id)arg3 atIndexPath:(id)arg4;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)_indexPathOfReferenceItemForLayoutTransitionInCollectionView:(id)arg1;
- (id)collectionView:(id)arg1 transitionLayoutForOldLayout:(id)arg2 newLayout:(id)arg3;
- (id)visibleCellForCity:(id)arg1;
- (long long)weatherModeForCell:(id)arg1 atIndexPath:(id)arg2;
- (void)configureCell:(id)arg1 atIndexPath:(id)arg2;
- (id)weatherCellForItemAtIndexPath:(id)arg1;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)configureCollectionView;
- (void)setCollectionView:(id)arg1;
- (long long)preferredStatusBarStyle;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

@end

