//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAAbstractCollectionViewController.h"

#import "UIGestureRecognizerDelegate.h"
#import "UIViewControllerPreviewingDelegate_Private.h"
#import "WACardLayoutDelegate.h"
#import "WAWeatherCollectionFooterViewCellDelegate.h"

@class NSIndexPath, NSLayoutConstraint, NSString, NSTimer, UILongPressGestureRecognizer, UIPanGestureRecognizer, UITapGestureRecognizer, UIView, WAPageCollectionViewController, WAPlaceholderCell, WAReorderableCardLayout;

@interface WACardCollectionViewController : WAAbstractCollectionViewController <UIViewControllerPreviewingDelegate_Private, WACardLayoutDelegate, UIGestureRecognizerDelegate, WAWeatherCollectionFooterViewCellDelegate>
{
    _Bool _shouldReloadCitiesAfterFinishedDragging;
    _Bool _longPressWasCancelled;
    id <WACardCollectionViewControllerDelegate> _delegate;
    WAReorderableCardLayout *_cardLayout;
    NSTimer *_timeHeartbeat;
    UIView *_multiCityKeyLine;
    UILongPressGestureRecognizer *_longPressRecognizer;
    UITapGestureRecognizer *_tapRecognizer;
    UIPanGestureRecognizer *_deleteSwipeRecognizer;
    UIPanGestureRecognizer *_cancelDeleteRecognizer;
    NSIndexPath *_swipingIndexPath;
    WAPlaceholderCell *_draggedView;
    NSLayoutConstraint *_draggedViewXPositionConstraint;
    NSLayoutConstraint *_draggedViewYPositionConstraint;
    NSTimer *_autoscrollTimer;
    long long _initialDragIndex;
    id <UIViewControllerPreviewing_Private> _previewing;
    WAPageCollectionViewController *_previewViewController;
    struct CGPoint _swipePoint;
    struct CGPoint _panPoint;
}

@property(retain, nonatomic) WAPageCollectionViewController *previewViewController; // @synthesize previewViewController=_previewViewController;
@property(retain, nonatomic) id <UIViewControllerPreviewing_Private> previewing; // @synthesize previewing=_previewing;
@property(nonatomic) long long initialDragIndex; // @synthesize initialDragIndex=_initialDragIndex;
@property(nonatomic) _Bool longPressWasCancelled; // @synthesize longPressWasCancelled=_longPressWasCancelled;
@property(retain, nonatomic) NSTimer *autoscrollTimer; // @synthesize autoscrollTimer=_autoscrollTimer;
@property(retain, nonatomic) NSLayoutConstraint *draggedViewYPositionConstraint; // @synthesize draggedViewYPositionConstraint=_draggedViewYPositionConstraint;
@property(retain, nonatomic) NSLayoutConstraint *draggedViewXPositionConstraint; // @synthesize draggedViewXPositionConstraint=_draggedViewXPositionConstraint;
@property(retain, nonatomic) WAPlaceholderCell *draggedView; // @synthesize draggedView=_draggedView;
@property(nonatomic) struct CGPoint panPoint; // @synthesize panPoint=_panPoint;
@property(retain, nonatomic) NSIndexPath *swipingIndexPath; // @synthesize swipingIndexPath=_swipingIndexPath;
@property(nonatomic) struct CGPoint swipePoint; // @synthesize swipePoint=_swipePoint;
@property(retain, nonatomic) UIPanGestureRecognizer *cancelDeleteRecognizer; // @synthesize cancelDeleteRecognizer=_cancelDeleteRecognizer;
@property(retain, nonatomic) UIPanGestureRecognizer *deleteSwipeRecognizer; // @synthesize deleteSwipeRecognizer=_deleteSwipeRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *tapRecognizer; // @synthesize tapRecognizer=_tapRecognizer;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressRecognizer; // @synthesize longPressRecognizer=_longPressRecognizer;
@property(retain, nonatomic) UIView *multiCityKeyLine; // @synthesize multiCityKeyLine=_multiCityKeyLine;
@property(retain, nonatomic) NSTimer *timeHeartbeat; // @synthesize timeHeartbeat=_timeHeartbeat;
@property(nonatomic) _Bool shouldReloadCitiesAfterFinishedDragging; // @synthesize shouldReloadCitiesAfterFinishedDragging=_shouldReloadCitiesAfterFinishedDragging;
@property(retain, nonatomic) WAReorderableCardLayout *cardLayout; // @synthesize cardLayout=_cardLayout;
@property(nonatomic) __weak id <WACardCollectionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)animateShowingLocationPicker;
- (void)configureCell:(id)arg1 withLayoutAttributes:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)animateDeletionOfRowWithCell:(id)arg1;
- (void)tappedOverviewCell:(id)arg1;
- (_Bool)_isEditing;
- (void)longTapped:(id)arg1;
- (void)_stopAutoscrollTimer;
- (void)_swapCellsIfNecessary;
- (void)_autoscroll:(id)arg1;
- (void)deleteSwiping:(id)arg1;
- (void)_cancelDeletion;
- (void)cancelDeletion:(id)arg1;
@property(readonly, nonatomic) _Bool isReordering;
- (void)didDismissPreviewViewController:(id)arg1 committing:(_Bool)arg2;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)committedViewControllerForPreviewViewController:(id)arg1;
- (void)willPresentPreviewViewController:(id)arg1 forItemAtIndexPath:(id)arg2;
- (id)previewViewControllerForItemAtIndexPath:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)updateTimeLabels;
- (void)endClockUpdates;
- (void)beginClockUpdates;
- (void)didTransitionToSize:(struct CGSize)arg1;
- (void)animateTransitionToSize:(struct CGSize)arg1;
- (void)willTransitionToSize:(struct CGSize)arg1;
- (void)updateAddButtonState;
- (void)showKeyLine:(_Bool)arg1;
- (id)collectionViewForLayout:(id)arg1;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)setCities:(id)arg1;
- (_Bool)canStartTransitionToMode:(unsigned long long)arg1;
- (void)orderSubviews;
- (long long)weatherModeForCell:(id)arg1 atIndexPath:(id)arg2;
- (void)configureCollectionView;
- (void)viewWillLayoutSubviews;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

