//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewLayout.h"

#import "WACollectionViewLayoutProtocol.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface WACardLayout : UICollectionViewLayout <WACollectionViewLayoutProtocol>
{
    unsigned long long _numOfItems;
    struct CGSize _contentSize;
    struct CGSize _itemSize;
    struct CGRect *_itemFrames;
    NSMutableArray *_visibleAttributes;
    NSMutableDictionary *_cachedAttributes;
    id <WACardLayoutDelegate> _layoutDelegate;
    struct CGSize _footerReferenceSize;
}

@property(nonatomic) __weak id <WACardLayoutDelegate> layoutDelegate; // @synthesize layoutDelegate=_layoutDelegate;
@property(nonatomic) struct CGSize footerReferenceSize; // @synthesize footerReferenceSize=_footerReferenceSize;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (long long)targetIndexForProposedStartIndex:(long long)arg1 inRect:(struct CGRect)arg2;
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (struct CGRect)frameForItem:(long long)arg1;
- (struct CGSize)collectionViewContentSize;
- (void)prepareLayout;
- (id)collectionView;
- (double)cityViewPanOffsetForCell:(id)arg1 indexPath:(id)arg2 contentOffset:(struct CGPoint)arg3;
- (double)textTopMarginForItemAtIndexPath:(id)arg1;
- (double)viewTextTopMargin;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

