//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UINavigationControllerDelegate.h"
#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WeatherValidatorDelegate.h"

@class NSArray, NSMutableArray, NSString, NSTimer, UILabel, UISearchBar, UITableView;

@interface WACityPickerViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, WeatherValidatorDelegate, UINavigationControllerDelegate>
{
    UITableView *_completionTable;
    UILabel *_tablePlaceholderLabel;
    UISearchBar *_searchField;
    NSTimer *_hideSpinnerTimer;
    NSArray *_autocompletedLocations;
    NSArray *_geocodedLocations;
    _Bool _isShowing;
    _Bool _networkReachable;
    _Bool _keyboardShowing;
    unsigned long long _autocompleteValidationState;
    unsigned long long _geocodeValidationState;
    NSMutableArray *_localCities;
    NSMutableArray *_displayedLocations;
    NSTimer *_geocoderTimer;
    id _delegate;
}

+ (double)cellLeadingPadding;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (unsigned long long)navigationControllerSupportedInterfaceOrientations:(id)arg1;
- (void)_setGeocodeValidationState:(unsigned long long)arg1;
- (void)_setAutocompleteValidationState:(unsigned long long)arg1;
- (void)_updateCompletionTablePlacehoder;
- (void)_showLoadingPlaceholderText;
- (void)_updatePlaceholderLabel;
- (void)_hideCompletions;
- (void)_showCompletions;
- (void)_geocodeLocation;
- (void)_autocompleteLocation;
- (void)_cancelValidation;
- (void)geocoderTimerFired:(id)arg1;
- (void)cancelTimer;
- (void)_searchFieldTextDidChange:(id)arg1;
- (id)_cityAtIndex:(unsigned long long)arg1;
- (void)setNetworkReachable:(_Bool)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)didFailGeocodeWithError:(id)arg1;
- (void)didGeocodeLocation:(id)arg1;
- (void)didFailWithError:(id)arg1;
- (void)didValidateLocation:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)cancel;
- (void)viewDidLayoutSubviews;
- (void)_setGeocodedLocations:(id)arg1;
- (void)_setAutocompletedLocations:(id)arg1;
- (void)_updateDisplayedLocations;
- (void)_automaticKeyboardDidHide:(id)arg1;
- (void)_automaticKeyboardWillShow:(id)arg1;
- (_Bool)isLoading;
- (void)willHide;
- (void)didShow;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)viewDidLoad;
- (void)loadView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

