//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UINavigationControllerDelegate.h"
#import "UISplitViewControllerDelegate.h"
#import "WACardCollectionViewControllerDelegate.h"
#import "WACityPickerViewDelegate.h"
#import "WACollectionViewTransitionDelegate.h"
#import "WAPageCollectionViewControllerDelegate.h"
#import "WeatherUpdaterDelegate.h"

@class City, NSArray, NSString, NSTimer, UINavigationController, UISplitViewController, WACardCollectionViewController, WACityPickerViewController, WACollectionViewTransitionManager, WAPageCollectionViewController, WeatherPreferences;

@interface WAContainerViewController : UIViewController <WACardCollectionViewControllerDelegate, WAPageCollectionViewControllerDelegate, UINavigationControllerDelegate, UISplitViewControllerDelegate, WACollectionViewTransitionDelegate, WACityPickerViewDelegate, WeatherUpdaterDelegate>
{
    _Bool _shouldReloadCardCitiesAfterReorder;
    _Bool _shouldSetCardCitiesAfterReorder;
    _Bool _performedInitialCityLoad;
    _Bool _viewDidAppear;
    id <WAContainerViewControllerDelegate> _delegate;
    UISplitViewController *_splitViewController;
    WAPageCollectionViewController *_pageController;
    WACardCollectionViewController *_cardController;
    NSArray *_cities;
    WACollectionViewTransitionManager *_transitionManager;
    NSTimer *_updateTimer;
    WACityPickerViewController *_cityPickerViewController;
    UINavigationController *_cityPickerNavigationController;
    WeatherPreferences *_preferences;
}

+ (_Bool)_shouldForwardViewWillTransitionToSize;
@property(readonly, nonatomic) WeatherPreferences *preferences; // @synthesize preferences=_preferences;
@property(nonatomic) _Bool viewDidAppear; // @synthesize viewDidAppear=_viewDidAppear;
@property(nonatomic) _Bool performedInitialCityLoad; // @synthesize performedInitialCityLoad=_performedInitialCityLoad;
@property(retain, nonatomic) UINavigationController *cityPickerNavigationController; // @synthesize cityPickerNavigationController=_cityPickerNavigationController;
@property(retain, nonatomic) WACityPickerViewController *cityPickerViewController; // @synthesize cityPickerViewController=_cityPickerViewController;
@property(retain, nonatomic) NSTimer *updateTimer; // @synthesize updateTimer=_updateTimer;
@property(nonatomic) _Bool shouldSetCardCitiesAfterReorder; // @synthesize shouldSetCardCitiesAfterReorder=_shouldSetCardCitiesAfterReorder;
@property(nonatomic) _Bool shouldReloadCardCitiesAfterReorder; // @synthesize shouldReloadCardCitiesAfterReorder=_shouldReloadCardCitiesAfterReorder;
@property(retain, nonatomic) WACollectionViewTransitionManager *transitionManager; // @synthesize transitionManager=_transitionManager;
@property(retain, nonatomic) NSArray *cities; // @synthesize cities=_cities;
@property(retain, nonatomic) WACardCollectionViewController *cardController; // @synthesize cardController=_cardController;
@property(retain, nonatomic) WAPageCollectionViewController *pageController; // @synthesize pageController=_pageController;
@property(retain, nonatomic) UISplitViewController *splitViewController; // @synthesize splitViewController=_splitViewController;
@property(nonatomic) __weak id <WAContainerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (long long)targetDisplayModeForActionInSplitViewController:(id)arg1;
- (_Bool)splitViewController:(id)arg1 showDetailViewController:(id)arg2 sender:(id)arg3;
- (id)splitViewController:(id)arg1 separateSecondaryViewControllerFromPrimaryViewController:(id)arg2;
- (_Bool)splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3;
- (_Bool)collectionViewTransitionManager:(id)arg1 canStartPinchingCityAtIndex:(long long)arg2;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (id)navigationController:(id)arg1 interactionControllerForAnimationController:(id)arg2;
- (void)cardCollectionViewController:(id)arg1 showCityPickerAnimated:(_Bool)arg2;
- (void)pageCollectionViewController:(id)arg1 showCardListFromCityAtIndex:(long long)arg2;
- (void)cardCollectionViewControllerPreviewDidDismiss;
- (void)cardCollectionViewControllerDidFinishReorder:(id)arg1;
- (void)cardCollectionViewController:(id)arg1 deleteCityAtIndex:(long long)arg2;
- (void)cardCollectionViewController:(id)arg1 exchangeCityAtIndex:(long long)arg2 withCityAtIndex:(long long)arg3;
- (void)cardCollectionViewController:(id)arg1 showCityAtIndex:(long long)arg2 animated:(_Bool)arg3;
- (void)cardCollectionViewController:(id)arg1 showCityAtIndex:(long long)arg2;
- (void)addLocation:(id)arg1;
- (void)hideLocationPickerAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showLocationPickerAnimated:(_Bool)arg1;
- (id)controllerForCollectionView:(id)arg1;
- (void)addLocalWeatherCityIfNeeded:(CDUnknownBlockType)arg1;
- (void)setLocalWeatherEnabled:(_Bool)arg1;
- (void)reloadLocalCity;
- (id)displayedLocalWeatherCity;
- (void)_updateLocalWeather;
- (void)updateLocalCityWithCompletion:(CDUnknownBlockType)arg1;
- (void)updateUserCitiesWithCompletion:(CDUnknownBlockType)arg1;
- (void)setActiveCityIndex:(unsigned long long)arg1;
@property(readonly) City *activeCity;
- (void)setActiveCity:(id)arg1;
- (void)_updateCollectionViewsForChange:(CDUnknownBlockType)arg1 shouldAnimateBlock:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_updateCollectionViewsForChange:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_exchangeCityAtIndex:(long long)arg1 withCityAtIndex:(long long)arg2 saveImmediately:(_Bool)arg3;
- (void)exchangeCityAtIndex:(long long)arg1 withCityAtIndex:(long long)arg2;
- (void)_deleteCityAtIndex:(unsigned long long)arg1 animate:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)deleteCityAtIndex:(unsigned long long)arg1;
- (void)deleteCity:(id)arg1 animate:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)deleteCity:(id)arg1;
- (void)addAndUpdateViewsForCity:(id)arg1;
- (void)reloadCitiesFromPrefs;
- (void)reloadCities;
- (void)reloadCitiesAfterExternalAddition;
- (void)reloadFailedCities;
- (void)updateAllCities;
- (void)updateAllCitiesFromTimer:(id)arg1;
- (void)_notifyOfCityListPrefChange;
- (void)saveStateToDisk;
- (void)purgeTransientCities;
- (void)discardOldData;
- (id)_cityOverrides;
- (void)loadCities;
- (void)failedUpdate:(id)arg1;
- (void)refreshForLocaleChange;
- (void)resume;
- (void)suspend;
- (void)didUpdateWeather;
- (void)_startUpdateTimer;
- (void)_stopUpdateTimer;
- (_Bool)_splitViewIsCollapsed;
- (void)_prepareToShowPageViewControllerForInitialAppSetup;
- (void)showPageForCityAtIndex:(long long)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)showCardListFromCityAtIndex:(long long)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_reachabilityChanged:(id)arg1;
- (void)_updateSplitViewPreferredDisplayMode;
- (void)_updateOverrideTraitCollectionWithSize:(struct CGSize)arg1;
- (void)setCities:(id)arg1 reloadUI:(_Bool)arg2;
- (void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (long long)preferredStatusBarStyle;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithPreferences:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

