//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath, UICollectionViewCell;

@protocol WACollectionViewLayoutProtocol <NSObject>
- (double)cityViewPanOffsetForCell:(UICollectionViewCell *)arg1 indexPath:(NSIndexPath *)arg2 contentOffset:(struct CGPoint)arg3;
@end

