//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewTransitionLayout.h"

#import "WACollectionViewLayoutProtocol.h"

@class NSIndexPath, NSString;

@interface WACollectionViewTransitionLayout : UICollectionViewTransitionLayout <WACollectionViewLayoutProtocol>
{
    NSIndexPath *_pivotIndexPath;
    unsigned long long _transitionMode;
    struct CGPoint _initialOffsetPoint;
}

@property(nonatomic) unsigned long long transitionMode; // @synthesize transitionMode=_transitionMode;
@property(nonatomic) struct CGPoint initialOffsetPoint; // @synthesize initialOffsetPoint=_initialOffsetPoint;
@property(retain, nonatomic) NSIndexPath *pivotIndexPath; // @synthesize pivotIndexPath=_pivotIndexPath;
- (void).cxx_destruct;
- (double)cityViewPanOffsetForCell:(id)arg1 indexPath:(id)arg2 contentOffset:(struct CGPoint)arg3;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

