//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerAnimatedTransitioning.h"
#import "UIViewControllerInteractiveTransitioning.h"
#import "WAAnimationDelegate.h"
#import "WACardLayoutDelegate.h"
#import "WACollectionViewCellTransitionDelegate.h"

@class NSString, UICollectionView, UIColor, UIPinchGestureRecognizer, WACardCollectionViewController, WACollectionViewTransitionLayout, WAPageCollectionViewController, WATransitionCardLayout, WAWeatherCollectionViewCell;

@interface WACollectionViewTransitionManager : NSObject <WACardLayoutDelegate, WACollectionViewCellTransitionDelegate, WAAnimationDelegate, UIViewControllerAnimatedTransitioning, UIViewControllerInteractiveTransitioning>
{
    id <WACollectionViewTransitionDelegate> _delegate;
    UICollectionView *_collectionView;
    WAPageCollectionViewController *_pageController;
    WACardCollectionViewController *_cardController;
    long long _pivotCityIndex;
    unsigned long long _transitionMode;
    long long _transitionType;
    CDUnknownBlockType _transitionCompletion;
    UIPinchGestureRecognizer *_pinchRecognizer;
    WACollectionViewTransitionLayout *_transitionLayout;
    WATransitionCardLayout *_transitionCardLayout;
    double _transitionStartOffset;
    double _transitionEndOffset;
    double _initialScale;
    id <UIViewControllerContextTransitioning> _transitionContext;
    WAWeatherCollectionViewCell *_pivotCell;
    UIColor *_savedEndViewControllerBackgroundColor;
}

@property(retain, nonatomic) UIColor *savedEndViewControllerBackgroundColor; // @synthesize savedEndViewControllerBackgroundColor=_savedEndViewControllerBackgroundColor;
@property(retain, nonatomic) WAWeatherCollectionViewCell *pivotCell; // @synthesize pivotCell=_pivotCell;
@property(retain, nonatomic) id <UIViewControllerContextTransitioning> transitionContext; // @synthesize transitionContext=_transitionContext;
@property(nonatomic) double initialScale; // @synthesize initialScale=_initialScale;
@property(nonatomic) double transitionEndOffset; // @synthesize transitionEndOffset=_transitionEndOffset;
@property(nonatomic) double transitionStartOffset; // @synthesize transitionStartOffset=_transitionStartOffset;
@property(retain, nonatomic) WATransitionCardLayout *transitionCardLayout; // @synthesize transitionCardLayout=_transitionCardLayout;
@property(retain, nonatomic) WACollectionViewTransitionLayout *transitionLayout; // @synthesize transitionLayout=_transitionLayout;
@property(retain, nonatomic) UIPinchGestureRecognizer *pinchRecognizer; // @synthesize pinchRecognizer=_pinchRecognizer;
@property(copy, nonatomic) CDUnknownBlockType transitionCompletion; // @synthesize transitionCompletion=_transitionCompletion;
@property(nonatomic) long long transitionType; // @synthesize transitionType=_transitionType;
@property(nonatomic) unsigned long long transitionMode; // @synthesize transitionMode=_transitionMode;
@property(nonatomic) long long pivotCityIndex; // @synthesize pivotCityIndex=_pivotCityIndex;
@property(retain, nonatomic) WACardCollectionViewController *cardController; // @synthesize cardController=_cardController;
@property(retain, nonatomic) WAPageCollectionViewController *pageController; // @synthesize pageController=_pageController;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) __weak id <WACollectionViewTransitionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)animation:(id)arg1 didUpdateProgress:(double)arg2;
- (void)collectionViewController:(id)arg1 configureTransitionLayoutForCell:(id)arg2 indexPath:(id)arg3;
- (id)transitionPivotIndexPathForCollectionViewController:(id)arg1;
- (unsigned long long)transitionModeForCollectionViewController:(id)arg1;
- (id)collectionViewForLayout:(id)arg1;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (void)startInteractiveTransition:(id)arg1;
- (void)handlePinch:(id)arg1;
- (double)transitionalParallaxOffsetForCellAtItemIndex:(long long)arg1;
- (void)_endTransition:(_Bool)arg1 immediately:(_Bool)arg2;
- (void)_cleanUpTransition:(_Bool)arg1 endMode:(long long)arg2;
- (void)_setTransitionProgress:(double)arg1;
- (void)_preparePageForTransitionFromOverview;
- (void)_prepareOverviewForTransitionFromPage;
- (_Bool)_prepareTransition;
- (_Bool)isTransitioning;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

