//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UILabel;

@interface WADeleteConfirmationButton : UIButton
{
    UILabel *_titleLabel;
    double _idealWidth;
}

+ (id)confirmationButtonWithTitle:(id)arg1 target:(id)arg2 selector:(SEL)arg3 backgroundColor:(id)arg4;
@property(nonatomic) double idealWidth; // @synthesize idealWidth=_idealWidth;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

