//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAAbstractCollectionViewController.h"

#import "UIGestureRecognizerDelegate.h"
#import "WAAssetLoaderDelegate.h"

@class CLLocation, City, NSString, TabScrollIndicatorView, UICollectionView, UILabel, UITapGestureRecognizer, UIView, WAPagedFlowLayout, WATouchButton, WAWeatherCollectionViewCell, WUIWeatherConditionBackgroundView;

@interface WAPageCollectionViewController : WAAbstractCollectionViewController <WAAssetLoaderDelegate, UIGestureRecognizerDelegate>
{
    _Bool _pageControlUsed;
    _Bool _hasPerformedInitialLayout;
    id <WAPageCollectionViewControllerDelegate> _delegate;
    City *_activeCity;
    WAPagedFlowLayout *_pageLayout;
    WUIWeatherConditionBackgroundView *_conditionBackgroundView;
    TabScrollIndicatorView *_tabScrollIndicatorView;
    UILabel *_conditionLabel;
    UILabel *_descriptionLabel;
    City *_nextCity;
    UITapGestureRecognizer *_pageSwitchRecognizer;
    WATouchButton *_infoButton;
    WATouchButton *_twcButton;
    UIView *_bottomDivider;
    WAWeatherCollectionViewCell *_transitionCell;
    UICollectionView *_transitionView;
    unsigned long long _initialActiveCityIndex;
    UITapGestureRecognizer *_debugModeRecognizer;
    CLLocation *_debugLocation;
    UILabel *_debugLabel;
    NSString *_debugState;
    UITapGestureRecognizer *_debugShowInMapsRecognizer;
}

+ (id)setupNewPageLayout;
@property(retain, nonatomic) UITapGestureRecognizer *debugShowInMapsRecognizer; // @synthesize debugShowInMapsRecognizer=_debugShowInMapsRecognizer;
@property(retain, nonatomic) NSString *debugState; // @synthesize debugState=_debugState;
@property(retain, nonatomic) UILabel *debugLabel; // @synthesize debugLabel=_debugLabel;
@property(retain, nonatomic) CLLocation *debugLocation; // @synthesize debugLocation=_debugLocation;
@property(retain, nonatomic) UITapGestureRecognizer *debugModeRecognizer; // @synthesize debugModeRecognizer=_debugModeRecognizer;
@property(nonatomic) unsigned long long initialActiveCityIndex; // @synthesize initialActiveCityIndex=_initialActiveCityIndex;
@property(nonatomic) _Bool hasPerformedInitialLayout; // @synthesize hasPerformedInitialLayout=_hasPerformedInitialLayout;
@property(retain, nonatomic) UICollectionView *transitionView; // @synthesize transitionView=_transitionView;
@property(retain, nonatomic) WAWeatherCollectionViewCell *transitionCell; // @synthesize transitionCell=_transitionCell;
@property(retain, nonatomic) UIView *bottomDivider; // @synthesize bottomDivider=_bottomDivider;
@property(retain, nonatomic) WATouchButton *twcButton; // @synthesize twcButton=_twcButton;
@property(retain, nonatomic) WATouchButton *infoButton; // @synthesize infoButton=_infoButton;
@property(retain, nonatomic) UITapGestureRecognizer *pageSwitchRecognizer; // @synthesize pageSwitchRecognizer=_pageSwitchRecognizer;
@property(retain, nonatomic) City *nextCity; // @synthesize nextCity=_nextCity;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UILabel *conditionLabel; // @synthesize conditionLabel=_conditionLabel;
@property(retain, nonatomic) TabScrollIndicatorView *tabScrollIndicatorView; // @synthesize tabScrollIndicatorView=_tabScrollIndicatorView;
@property(nonatomic) _Bool pageControlUsed; // @synthesize pageControlUsed=_pageControlUsed;
@property(retain, nonatomic) WUIWeatherConditionBackgroundView *conditionBackgroundView; // @synthesize conditionBackgroundView=_conditionBackgroundView;
@property(retain, nonatomic) WAPagedFlowLayout *pageLayout; // @synthesize pageLayout=_pageLayout;
@property(retain, nonatomic) City *activeCity; // @synthesize activeCity=_activeCity;
@property(nonatomic) __weak id <WAPageCollectionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateDUETDebugMessage:(unsigned long long)arg1 weatherDetail:(unsigned long long)arg2 andLocalDetail:(unsigned long long)arg3;
- (void)_updateBackgroundForSunHeightChange:(id)arg1;
- (void)_iterateConditions:(_Bool)arg1;
- (void)setDebugConditionCode:(long long)arg1 isNight:(_Bool)arg2;
- (void)_previousCondition:(id)arg1;
- (void)_nextCondition:(id)arg1;
- (void)_showLocation:(id)arg1;
- (void)_setRestState:(id)arg1;
- (void)_setNetworkState:(id)arg1;
- (void)_setLocationState:(id)arg1;
- (void)_updateDebugDisplay;
- (void)updateLocInformation:(id)arg1;
- (id)_debugString;
- (void)cityViewPressedInfoButton:(id)arg1;
- (void)_reLayoutBottomToolbarWithFrame:(struct CGRect)arg1;
- (void)twcButtonPressed;
- (void)infoButtonPressed;
- (void)_relayoutIndicatorView;
- (void)reloadIndicatorView:(id)arg1;
- (void)_animateSlideLeft:(_Bool)arg1;
- (void)indicatorSelectionChanged:(id)arg1;
- (void)resetTabScrollIndicator;
- (void)setupTabScrollIndicatorView;
- (void)switchPages:(id)arg1;
- (void)updateExtendedWeatherOnVisibleCells;
- (void)didUpdateWeather;
- (void)reflowConditions;
- (void)updateAndDisplayActiveCity;
@property(nonatomic) unsigned long long activeCityIndex;
- (long long)setActiveCityWithCoordinate:(CDStruct_c3b9c2ee)arg1 localCity:(_Bool)arg2;
- (void)setActiveCity:(id)arg1 shouldScroll:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)_updateScrollerViewsLater;
- (void)_updateScrollerViews;
- (void)_resetActiveCityPanOffset;
- (void)_setScrollPointToActiveCity;
- (float)_offsetForDocument:(unsigned long long)arg1;
- (int)_documentForOffset:(float)arg1;
- (void)setChromeAlphaWithProgress:(double)arg1 transitionMode:(unsigned long long)arg2;
- (void)putBackConditionViewFromCell:(id)arg1;
- (void)removeExtraViewsFromCell:(id)arg1;
- (void)addExtraViewsToCell:(id)arg1 atIndexPath:(id)arg2 transitionMode:(unsigned long long)arg3;
- (void)_tileWithFrame:(struct CGRect)arg1;
- (void)updateBackground;
- (void)didTransitionToSize:(struct CGSize)arg1;
- (void)animateTransitionToSize:(struct CGSize)arg1;
- (void)willTransitionToSize:(struct CGSize)arg1;
- (void)discardTransitionCell;
- (void)createTransitionCellForOldViewSize:(struct CGSize)arg1;
- (id)collectionViewLayout;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)prepareForReuse;
- (void)reloadData;
- (void)orderSubviews;
- (long long)weatherModeForCell:(id)arg1 atIndexPath:(id)arg2;
- (void)configureCollectionView;
- (void)resetAssetLoaderDelegate;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithInitialActiveCityIndex:(unsigned long long)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

