//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewFlowLayout.h"

#import "WACollectionViewLayoutProtocol.h"

@class NSIndexPath, NSString;

@interface WAPagedFlowLayout : UICollectionViewFlowLayout <WACollectionViewLayoutProtocol>
{
    NSIndexPath *_targetIndexPath;
}

@property(retain, nonatomic) NSIndexPath *targetIndexPath; // @synthesize targetIndexPath=_targetIndexPath;
- (void).cxx_destruct;
- (double)cityViewPanOffsetForCell:(id)arg1 indexPath:(id)arg2 contentOffset:(struct CGPoint)arg3;
- (struct CGPoint)targetContentOffsetForProposedContentOffset:(struct CGPoint)arg1 withScrollingVelocity:(struct CGPoint)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

