//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WACardLayout.h"

@class NSIndexPath;

@interface WAReorderableCardLayout : WACardLayout
{
    _Bool _isReordering;
    NSIndexPath *_deleteIndexPath;
    NSIndexPath *_pivotIndexPath;
    long long _initialDragIndex;
    long long _currentDragIndex;
}

@property(nonatomic) long long currentDragIndex; // @synthesize currentDragIndex=_currentDragIndex;
@property(readonly, nonatomic) long long initialDragIndex; // @synthesize initialDragIndex=_initialDragIndex;
@property(retain, nonatomic) NSIndexPath *pivotIndexPath; // @synthesize pivotIndexPath=_pivotIndexPath;
@property(retain, nonatomic) NSIndexPath *deleteIndexPath; // @synthesize deleteIndexPath=_deleteIndexPath;
- (void).cxx_destruct;
- (_Bool)isReordering;
- (void)endReordering;
- (void)beginReorderingWithInitialDragIndex:(long long)arg1;
- (long long)targetIndexForProposedStartIndex:(long long)arg1 inRect:(struct CGRect)arg2;
- (struct CGPoint)targetContentOffsetForProposedContentOffset:(struct CGPoint)arg1;
- (long long)indexForItemAtPoint:(struct CGPoint)arg1;
- (id)finalLayoutAttributesForDisappearingItemAtIndexPath:(id)arg1;

@end

