//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WACardLayout.h"

@class NSIndexPath;

@interface WATransitionCardLayout : WACardLayout
{
    double _pivotHeight;
    NSIndexPath *_pivotIndexPath;
}

@property(retain, nonatomic) NSIndexPath *pivotIndexPath; // @synthesize pivotIndexPath=_pivotIndexPath;
- (void).cxx_destruct;
- (struct CGRect)frameForItem:(long long)arg1;
- (struct CGPoint)targetContentOffsetForProposedContentOffset:(struct CGPoint)arg1;
- (void)prepareLayout;

@end

