//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint, NSString, UIImageView, UILabel;

@interface WAWeatherCardView : UIView
{
    UIImageView *_locationIndicatorView;
    NSString *_cityName;
    _Bool _isLocalWeatherCity;
    UILabel *_timeLabel;
    UILabel *_temperatureLabel;
    UIImageView *_cityNameImage;
    NSLayoutConstraint *_cityNameLeadingConstraint;
    NSLayoutConstraint *_cityNameBottomConstraint;
    NSLayoutConstraint *_cityNameAspectRatio;
}

+ (id)locationIndicatorImage;
@property(retain, nonatomic) NSLayoutConstraint *cityNameAspectRatio; // @synthesize cityNameAspectRatio=_cityNameAspectRatio;
@property(retain, nonatomic) NSLayoutConstraint *cityNameBottomConstraint; // @synthesize cityNameBottomConstraint=_cityNameBottomConstraint;
@property(retain, nonatomic) NSLayoutConstraint *cityNameLeadingConstraint; // @synthesize cityNameLeadingConstraint=_cityNameLeadingConstraint;
@property(retain, nonatomic) UIImageView *cityNameImage; // @synthesize cityNameImage=_cityNameImage;
@property(nonatomic) _Bool isLocalWeatherCity; // @synthesize isLocalWeatherCity=_isLocalWeatherCity;
@property(readonly, nonatomic) UILabel *temperatureLabel; // @synthesize temperatureLabel=_temperatureLabel;
@property(readonly, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
- (void).cxx_destruct;
- (void)createConstraints;
- (void)createLocationIndicatorConstraints;
- (void)updateCityNameConstraints;
@property(retain, nonatomic) NSString *cityName;
- (id)initWithFrame:(struct CGRect)arg1;

@end

