//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "CityUpdateObserver.h"

@class City, NSArray, NSString, UIButton, WAWeatherCityView, WUIDynamicWeatherBackground;

@interface WAWeatherCollectionViewCell : UICollectionViewCell <CityUpdateObserver>
{
    double _buttonWidth;
    _Bool _showingDeleteUI;
    _Bool _needsUIUpdateAfterReuse;
    City *_city;
    long long _mode;
    double _transitionProgress;
    double _textTopMargin;
    UIButton *_deleteButton;
    id <WAWeatherCollectionViewCellDelegate> _delegate;
    id <WAWeatherCollectionViewCellLayoutDelegate> _layoutDelegate;
    WUIDynamicWeatherBackground *_background;
    NSArray *_extraViews;
    WAWeatherCityView *_cityView;
    double _deleteSliderOffset;
}

@property(nonatomic) _Bool needsUIUpdateAfterReuse; // @synthesize needsUIUpdateAfterReuse=_needsUIUpdateAfterReuse;
@property(nonatomic) double deleteSliderOffset; // @synthesize deleteSliderOffset=_deleteSliderOffset;
@property(readonly, nonatomic) WAWeatherCityView *cityView; // @synthesize cityView=_cityView;
@property(retain, nonatomic) NSArray *extraViews; // @synthesize extraViews=_extraViews;
@property(retain, nonatomic) WUIDynamicWeatherBackground *background; // @synthesize background=_background;
@property(nonatomic) __weak id <WAWeatherCollectionViewCellLayoutDelegate> layoutDelegate; // @synthesize layoutDelegate=_layoutDelegate;
@property(nonatomic) __weak id <WAWeatherCollectionViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(readonly, nonatomic, getter=isShowingDeleteUI) _Bool showingDeleteUI; // @synthesize showingDeleteUI=_showingDeleteUI;
@property(nonatomic) double textTopMargin; // @synthesize textTopMargin=_textTopMargin;
@property(nonatomic) double transitionProgress; // @synthesize transitionProgress=_transitionProgress;
@property(readonly, nonatomic) long long mode; // @synthesize mode=_mode;
@property(readonly, nonatomic) City *city; // @synthesize city=_city;
- (void).cxx_destruct;
- (void)didTransitionToSize:(struct CGSize)arg1;
- (void)animateTransitionToSize:(struct CGSize)arg1 layoutOptions:(id)arg2;
- (void)willTransitionToSize:(struct CGSize)arg1 layoutOptions:(id)arg2;
- (void)setParallaxOffset:(double)arg1 isTransitionOffset:(_Bool)arg2;
- (void)setContentOffset:(struct CGPoint)arg1 cityViewPanOffset:(double)arg2;
- (void)applyLayoutAttributes:(id)arg1;
- (void)useBackgroundView:(id)arg1;
- (void)delete:(id)arg1;
- (void)_layoutForShowingDeleteUI:(_Bool)arg1;
- (double)deleteButtonWidthForOffset:(double)arg1;
- (double)deleteButtonOriginXForOffset:(double)arg1;
- (void)showDeleteUI:(_Bool)arg1 animated:(_Bool)arg2;
- (void)swipeByOffset:(double)arg1;
- (void)beginTracking;
- (void)refreshForUnitsChange;
- (void)setCity:(id)arg1 andMode:(long long)arg2;
- (void)cityDidStartWeatherUpdate:(id)arg1;
- (void)cityDidFinishWeatherUpdate:(id)arg1;
- (void)_updateBackgroundCondition;
- (void)prepareForReuse;
- (void)dealloc;
- (void)useCityView:(id)arg1;
- (id)relinquishCityView;
- (id)relinquishBackground;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_createCityView;
- (void)_createBackground;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

