//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CPBitmapStore, NSCache, NSLock, NSObject<OS_dispatch_queue>;

@interface WAWeatherUILabelCache : NSObject
{
    CPBitmapStore *_store;
    NSLock *_storeLock;
    NSCache *_temperatureLabels;
    NSCache *_monospacedTemperatureLabels;
    NSCache *_lightTemperatureLabels;
    NSCache *_monospacedLightTemperatureLabels;
    NSCache *_boldTemperatureLabels;
    NSCache *_precipitationLabels;
    NSCache *_cityCardNameLabels;
    NSCache *_cityCardNameBaselines;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (struct UIEdgeInsets)outsetsForString:(id)arg1 withLabelType:(unsigned long long)arg2;
+ (double)baselineForCityCardName:(id)arg1 withWindowWidth:(double)arg2;
+ (id)imageForCityCardName:(id)arg1 withWindowWidth:(double)arg2;
+ (id)imageForPrecipitation:(id)arg1;
+ (id)imageForTemperature:(id)arg1 withStyle:(unsigned long long)arg2;
+ (id)_attributesForCreatingTemperatureImageWithLabelStyle:(unsigned long long)arg1;
+ (id)imageForWeekday:(id)arg1 withStyle:(unsigned long long)arg2;
+ (id)imageForWeekday:(id)arg1;
+ (id)imageForTime:(id)arg1 bold:(_Bool)arg2;
+ (void)_slowlyPrecacheTemperatures;
+ (void)precacheWeekdays;
+ (void)_slowlyPrecacheLocalizedTimes:(id)arg1;
+ (id)_localizedTimesToPrecache;
+ (void)precacheLabels;
+ (id)imageForLabelWithText:(id)arg1 withLightlabel:(_Bool)arg2;
+ (id)imageForLabelWithText:(id)arg1 withLightlabel:(_Bool)arg2 withFont:(id)arg3;
+ (id)attributesForType:(unsigned long long)arg1;
+ (id)imageForAttributedString:(id)arg1;
+ (id)imageForString:(id)arg1 attributes:(id)arg2;
+ (id)imageForString:(id)arg1 attributes:(id)arg2 size:(struct CGSize)arg3 baselineOffset:(double *)arg4 outsets:(struct UIEdgeInsets *)arg5;
+ (struct UIEdgeInsets)outsetsForFont:(id)arg1;
+ (id)excessiveLineHeightCharacterSet;
+ (id)imageForString:(id)arg1 attributes:(id)arg2 size:(struct CGSize)arg3 baselineOffset:(double *)arg4;
+ (id)sharedUILabelCache;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSCache *cityCardNameBaselines; // @synthesize cityCardNameBaselines=_cityCardNameBaselines;
@property(retain, nonatomic) NSCache *cityCardNameLabels; // @synthesize cityCardNameLabels=_cityCardNameLabels;
@property(retain, nonatomic) NSCache *precipitationLabels; // @synthesize precipitationLabels=_precipitationLabels;
@property(retain, nonatomic) NSCache *boldTemperatureLabels; // @synthesize boldTemperatureLabels=_boldTemperatureLabels;
@property(retain, nonatomic) NSCache *monospacedLightTemperatureLabels; // @synthesize monospacedLightTemperatureLabels=_monospacedLightTemperatureLabels;
@property(retain, nonatomic) NSCache *lightTemperatureLabels; // @synthesize lightTemperatureLabels=_lightTemperatureLabels;
@property(retain, nonatomic) NSCache *monospacedTemperatureLabels; // @synthesize monospacedTemperatureLabels=_monospacedTemperatureLabels;
@property(retain, nonatomic) NSCache *temperatureLabels; // @synthesize temperatureLabels=_temperatureLabels;
@property(retain, nonatomic) NSLock *storeLock; // @synthesize storeLock=_storeLock;
@property(retain, nonatomic) CPBitmapStore *store; // @synthesize store=_store;
- (void).cxx_destruct;
- (id)cachedImageForWeekday:(id)arg1 withStyle:(unsigned long long)arg2;
- (id)cachedImageForWeekday:(id)arg1;
- (id)cachedImageForTime:(id)arg1 bold:(_Bool)arg2;
- (void)userTextSizeDidChange;
- (void)resetLocale;
- (void)deleteAndCreateCache;
- (void)dealloc;
- (id)init;

@end

