//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class UIButton, WATouchButton, WAUnitSelectionControl;

@interface WAWeatherCollectionFooterViewCell : UICollectionReusableView
{
    id <WAWeatherCollectionFooterViewCellDelegate> _delegate;
    WATouchButton *_addButton;
    WAUnitSelectionControl *_unitControl;
    UIButton *_theWeatherChannelButton;
}

@property(retain, nonatomic) UIButton *theWeatherChannelButton; // @synthesize theWeatherChannelButton=_theWeatherChannelButton;
@property(retain, nonatomic) WAUnitSelectionControl *unitControl; // @synthesize unitControl=_unitControl;
@property(retain, nonatomic) WATouchButton *addButton; // @synthesize addButton=_addButton;
@property(nonatomic) __weak id <WAWeatherCollectionFooterViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_showAddSheet:(id)arg1;
- (void)_selectedSegmentChanged:(id)arg1;
- (void)_twcLogoTapped:(id)arg1;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (void)_updateUnitControl;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

