//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WAWeatherCityViewLayoutOptions : NSObject
{
    long long _columnConfiguration;
    long long _basicInfoConfiguration;
    long long _detailInfoConfiguration;
    double _pageScrollViewInset;
    double _overDividerY;
    double _underDividerY;
    double _edgePadding;
    double _pageFontSize;
    double _pageDegreeFontSize;
    double _pageBaselineOffset;
    double _pageCityNameFontSize;
    double _conditionBaseline;
    double _temperatureFontSize;
    double _pageScrollViewOriginY;
    double _headerMaximumScrollOffset;
    double _pageTemperatureFadeMultiplier;
    double _pageDayInfoFadeMultiplier;
    double _dayForecastLandscapeWidth;
    double _verticalDividerLateralPadding;
    double _verticalDividerToHorizontalDividerPadding;
    double _topToFirstBaselinePadding;
    double _lastBaselineToBottomPadding;
    double _interGroupPadding;
    long long _uid;
}

@property(nonatomic) long long uid; // @synthesize uid=_uid;
@property(nonatomic) double interGroupPadding; // @synthesize interGroupPadding=_interGroupPadding;
@property(nonatomic) double lastBaselineToBottomPadding; // @synthesize lastBaselineToBottomPadding=_lastBaselineToBottomPadding;
@property(nonatomic) double topToFirstBaselinePadding; // @synthesize topToFirstBaselinePadding=_topToFirstBaselinePadding;
@property(nonatomic) double verticalDividerToHorizontalDividerPadding; // @synthesize verticalDividerToHorizontalDividerPadding=_verticalDividerToHorizontalDividerPadding;
@property(nonatomic) double verticalDividerLateralPadding; // @synthesize verticalDividerLateralPadding=_verticalDividerLateralPadding;
@property(nonatomic) double dayForecastLandscapeWidth; // @synthesize dayForecastLandscapeWidth=_dayForecastLandscapeWidth;
@property(nonatomic) double pageDayInfoFadeMultiplier; // @synthesize pageDayInfoFadeMultiplier=_pageDayInfoFadeMultiplier;
@property(nonatomic) double pageTemperatureFadeMultiplier; // @synthesize pageTemperatureFadeMultiplier=_pageTemperatureFadeMultiplier;
@property(nonatomic) double headerMaximumScrollOffset; // @synthesize headerMaximumScrollOffset=_headerMaximumScrollOffset;
@property(nonatomic) double pageScrollViewOriginY; // @synthesize pageScrollViewOriginY=_pageScrollViewOriginY;
@property(nonatomic) double temperatureFontSize; // @synthesize temperatureFontSize=_temperatureFontSize;
@property(nonatomic) double conditionBaseline; // @synthesize conditionBaseline=_conditionBaseline;
@property(nonatomic) double pageCityNameFontSize; // @synthesize pageCityNameFontSize=_pageCityNameFontSize;
@property(nonatomic) double pageBaselineOffset; // @synthesize pageBaselineOffset=_pageBaselineOffset;
@property(nonatomic) double pageDegreeFontSize; // @synthesize pageDegreeFontSize=_pageDegreeFontSize;
@property(nonatomic) double pageFontSize; // @synthesize pageFontSize=_pageFontSize;
@property(nonatomic) double edgePadding; // @synthesize edgePadding=_edgePadding;
@property(nonatomic) double underDividerY; // @synthesize underDividerY=_underDividerY;
@property(nonatomic) double overDividerY; // @synthesize overDividerY=_overDividerY;
@property(nonatomic) double pageScrollViewInset; // @synthesize pageScrollViewInset=_pageScrollViewInset;
@property(nonatomic) long long detailInfoConfiguration; // @synthesize detailInfoConfiguration=_detailInfoConfiguration;
@property(nonatomic) long long basicInfoConfiguration; // @synthesize basicInfoConfiguration=_basicInfoConfiguration;
@property(nonatomic) long long columnConfiguration; // @synthesize columnConfiguration=_columnConfiguration;
- (void)_configureForRegulariPadTwoColumns;
- (void)_configureForRegulariPadOneColumn;
- (void)_configureForLargePhoneTwoColumns;
- (void)_configureForLargePhoneOneColumn;
- (void)_configureFor667Height;
- (void)_configureFor568Height;
- (void)_configureFor480Height;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithViewSize:(struct CGSize)arg1 traitCollection:(id)arg2;

@end

